# Site settings
title: Color Contrast Checker
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Check if there is enough contrast between the text color and
  the background color
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.colorcontrastchecker.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
